# coding: utf-8

"""
    Swagger for Utility Network

    Open API Specification (OAS/Swagger)  * **trace**, **updateIsConnected** from the [ArcGIS Utility Network]( https://developers.arcgis.com/rest/services-reference/utility-network-service.htm) * **generateToken** from the [ArcGIS REST API](https://developers.arcgis.com/rest/)  Tested on ArcGIS  Enterprise 10.6.1 using [NSwagStudio](https://github.com/RSuter/NSwag/wiki/NSwagStudio) C# code gen .   # noqa: E501

    OpenAPI spec version: 0.13
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class FunctionBarrier(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'function_type': 'str',
        'network_attribute_name': 'str',
        'operator': 'str',
        'value': 'str',
        'use_local_values': 'bool'
    }

    attribute_map = {
        'function_type': 'functionType',
        'network_attribute_name': 'networkAttributeName',
        'operator': 'operator',
        'value': 'value',
        'use_local_values': 'useLocalValues'
    }

    def __init__(self, function_type=None, network_attribute_name=None, operator=None, value=None, use_local_values=None):  # noqa: E501
        """FunctionBarrier - a model defined in Swagger"""  # noqa: E501

        self._function_type = None
        self._network_attribute_name = None
        self._operator = None
        self._value = None
        self._use_local_values = None
        self.discriminator = None

        self.function_type = function_type
        self.network_attribute_name = network_attribute_name
        self.operator = operator
        self.value = value
        if use_local_values is not None:
            self.use_local_values = use_local_values

    @property
    def function_type(self):
        """Gets the function_type of this FunctionBarrier.  # noqa: E501

        Choose from a number of different calculation functions.  # noqa: E501

        :return: The function_type of this FunctionBarrier.  # noqa: E501
        :rtype: str
        """
        return self._function_type

    @function_type.setter
    def function_type(self, function_type):
        """Sets the function_type of this FunctionBarrier.

        Choose from a number of different calculation functions.  # noqa: E501

        :param function_type: The function_type of this FunctionBarrier.  # noqa: E501
        :type: str
        """
        if function_type is None:
            raise ValueError("Invalid value for `function_type`, must not be `None`")  # noqa: E501
        allowed_values = ["add", "subtract", "average", "count", "min", "max"]  # noqa: E501
        if function_type not in allowed_values:
            raise ValueError(
                "Invalid value for `function_type` ({0}), must be one of {1}"  # noqa: E501
                .format(function_type, allowed_values)
            )

        self._function_type = function_type

    @property
    def network_attribute_name(self):
        """Gets the network_attribute_name of this FunctionBarrier.  # noqa: E501

        Choose to filter by any network attribute defined in the system.  # noqa: E501

        :return: The network_attribute_name of this FunctionBarrier.  # noqa: E501
        :rtype: str
        """
        return self._network_attribute_name

    @network_attribute_name.setter
    def network_attribute_name(self, network_attribute_name):
        """Sets the network_attribute_name of this FunctionBarrier.

        Choose to filter by any network attribute defined in the system.  # noqa: E501

        :param network_attribute_name: The network_attribute_name of this FunctionBarrier.  # noqa: E501
        :type: str
        """
        if network_attribute_name is None:
            raise ValueError("Invalid value for `network_attribute_name`, must not be `None`")  # noqa: E501

        self._network_attribute_name = network_attribute_name

    @property
    def operator(self):
        """Gets the operator of this FunctionBarrier.  # noqa: E501

        Choose from a number of different operators  # noqa: E501

        :return: The operator of this FunctionBarrier.  # noqa: E501
        :rtype: str
        """
        return self._operator

    @operator.setter
    def operator(self, operator):
        """Sets the operator of this FunctionBarrier.

        Choose from a number of different operators  # noqa: E501

        :param operator: The operator of this FunctionBarrier.  # noqa: E501
        :type: str
        """
        if operator is None:
            raise ValueError("Invalid value for `operator`, must not be `None`")  # noqa: E501
        allowed_values = ["equal", "notEqual", "greaterThan", "lessThan", "lessThanEqual", "includesTheValues", "doesNotIncludeTheValues", "includesAny", "doesNotIncludeAny"]  # noqa: E501
        if operator not in allowed_values:
            raise ValueError(
                "Invalid value for `operator` ({0}), must be one of {1}"  # noqa: E501
                .format(operator, allowed_values)
            )

        self._operator = operator

    @property
    def value(self):
        """Gets the value of this FunctionBarrier.  # noqa: E501

        Specific value of the input attribute type that, if discovered, will cause the termination.(string (numeric)  # noqa: E501

        :return: The value of this FunctionBarrier.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this FunctionBarrier.

        Specific value of the input attribute type that, if discovered, will cause the termination.(string (numeric)  # noqa: E501

        :param value: The value of this FunctionBarrier.  # noqa: E501
        :type: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def use_local_values(self):
        """Gets the use_local_values of this FunctionBarrier.  # noqa: E501

        Calculates values in each direction as opposed to an overall global value.  # noqa: E501

        :return: The use_local_values of this FunctionBarrier.  # noqa: E501
        :rtype: bool
        """
        return self._use_local_values

    @use_local_values.setter
    def use_local_values(self, use_local_values):
        """Sets the use_local_values of this FunctionBarrier.

        Calculates values in each direction as opposed to an overall global value.  # noqa: E501

        :param use_local_values: The use_local_values of this FunctionBarrier.  # noqa: E501
        :type: bool
        """

        self._use_local_values = use_local_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FunctionBarrier, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FunctionBarrier):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
