# coding: utf-8

"""
    Swagger for Utility Network

    Open API Specification (OAS/Swagger)  * **trace**, **updateIsConnected** from the [ArcGIS Utility Network]( https://developers.arcgis.com/rest/services-reference/utility-network-service.htm) * **generateToken** from the [ArcGIS REST API](https://developers.arcgis.com/rest/)  Tested on ArcGIS  Enterprise 10.6.1 using [NSwagStudio](https://github.com/RSuter/NSwag/wiki/NSwagStudio) C# code gen .   # noqa: E501

    OpenAPI spec version: 0.13
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class OutputFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'source_id': 'float',
        'asset_group': 'float',
        'asset_type': 'float'
    }

    attribute_map = {
        'source_id': 'sourceId',
        'asset_group': 'assetGroup',
        'asset_type': 'assetType'
    }

    def __init__(self, source_id=None, asset_group=None, asset_type=None):  # noqa: E501
        """OutputFilter - a model defined in Swagger"""  # noqa: E501

        self._source_id = None
        self._asset_group = None
        self._asset_type = None
        self.discriminator = None

        self.source_id = source_id
        self.asset_group = asset_group
        self.asset_type = asset_type

    @property
    def source_id(self):
        """Gets the source_id of this OutputFilter.  # noqa: E501


        :return: The source_id of this OutputFilter.  # noqa: E501
        :rtype: float
        """
        return self._source_id

    @source_id.setter
    def source_id(self, source_id):
        """Sets the source_id of this OutputFilter.


        :param source_id: The source_id of this OutputFilter.  # noqa: E501
        :type: float
        """
        if source_id is None:
            raise ValueError("Invalid value for `source_id`, must not be `None`")  # noqa: E501

        self._source_id = source_id

    @property
    def asset_group(self):
        """Gets the asset_group of this OutputFilter.  # noqa: E501


        :return: The asset_group of this OutputFilter.  # noqa: E501
        :rtype: float
        """
        return self._asset_group

    @asset_group.setter
    def asset_group(self, asset_group):
        """Sets the asset_group of this OutputFilter.


        :param asset_group: The asset_group of this OutputFilter.  # noqa: E501
        :type: float
        """
        if asset_group is None:
            raise ValueError("Invalid value for `asset_group`, must not be `None`")  # noqa: E501

        self._asset_group = asset_group

    @property
    def asset_type(self):
        """Gets the asset_type of this OutputFilter.  # noqa: E501


        :return: The asset_type of this OutputFilter.  # noqa: E501
        :rtype: float
        """
        return self._asset_type

    @asset_type.setter
    def asset_type(self, asset_type):
        """Sets the asset_type of this OutputFilter.


        :param asset_type: The asset_type of this OutputFilter.  # noqa: E501
        :type: float
        """
        if asset_type is None:
            raise ValueError("Invalid value for `asset_type`, must not be `None`")  # noqa: E501

        self._asset_type = asset_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OutputFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OutputFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
