/* 
 * Swagger for Utility Network
 *
 * Open API Specification (OAS/Swagger)  * **trace**, **updateIsConnected** from the [ArcGIS Utility Network](https://developers.arcgis.com/rest/services-reference/utility-network-service.htm) * **generateToken** from the [ArcGIS REST API](https://developers.arcgis.com/rest/)  Tested on ArcGIS  Enterprise 10.8.1 using OpenAPI Specification (OAC) written in [SwaggerEditor](https://github.com/swagger-api/swagger-editor)   and [SwaggerHub](https://app.swaggerhub.com/) for C# and Typescript-Angular code generation.  
 *
 * OpenAPI spec version: 3.0
 * Contact: kim.sundeen@sspinnovations.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Array of objects; optional parameter.
    /// </summary>
    [DataContract]
        public partial class FunctionBarrier :  IEquatable<FunctionBarrier>, IValidatableObject
    {
        /// <summary>
        /// Choose from a number of different calculation functions.
        /// </summary>
        /// <value>Choose from a number of different calculation functions.</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum FunctionTypeEnum
        {
            /// <summary>
            /// Enum Add for value: add
            /// </summary>
            [EnumMember(Value = "add")]
            Add = 1,
            /// <summary>
            /// Enum Subtract for value: subtract
            /// </summary>
            [EnumMember(Value = "subtract")]
            Subtract = 2,
            /// <summary>
            /// Enum Average for value: average
            /// </summary>
            [EnumMember(Value = "average")]
            Average = 3,
            /// <summary>
            /// Enum Count for value: count
            /// </summary>
            [EnumMember(Value = "count")]
            Count = 4,
            /// <summary>
            /// Enum Min for value: min
            /// </summary>
            [EnumMember(Value = "min")]
            Min = 5,
            /// <summary>
            /// Enum Max for value: max
            /// </summary>
            [EnumMember(Value = "max")]
            Max = 6        }
        /// <summary>
        /// Choose from a number of different calculation functions.
        /// </summary>
        /// <value>Choose from a number of different calculation functions.</value>
        [DataMember(Name="functionType", EmitDefaultValue=false)]
        public FunctionTypeEnum FunctionType { get; set; }
        /// <summary>
        /// Choose from a number of different operators
        /// </summary>
        /// <value>Choose from a number of different operators</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum OperatorEnum
        {
            /// <summary>
            /// Enum Equal for value: equal
            /// </summary>
            [EnumMember(Value = "equal")]
            Equal = 1,
            /// <summary>
            /// Enum NotEqual for value: notEqual
            /// </summary>
            [EnumMember(Value = "notEqual")]
            NotEqual = 2,
            /// <summary>
            /// Enum GreaterThan for value: greaterThan
            /// </summary>
            [EnumMember(Value = "greaterThan")]
            GreaterThan = 3,
            /// <summary>
            /// Enum LessThan for value: lessThan
            /// </summary>
            [EnumMember(Value = "lessThan")]
            LessThan = 4,
            /// <summary>
            /// Enum LessThanEqual for value: lessThanEqual
            /// </summary>
            [EnumMember(Value = "lessThanEqual")]
            LessThanEqual = 5,
            /// <summary>
            /// Enum IncludesTheValues for value: includesTheValues
            /// </summary>
            [EnumMember(Value = "includesTheValues")]
            IncludesTheValues = 6,
            /// <summary>
            /// Enum DoesNotIncludeTheValues for value: doesNotIncludeTheValues
            /// </summary>
            [EnumMember(Value = "doesNotIncludeTheValues")]
            DoesNotIncludeTheValues = 7,
            /// <summary>
            /// Enum IncludesAny for value: includesAny
            /// </summary>
            [EnumMember(Value = "includesAny")]
            IncludesAny = 8,
            /// <summary>
            /// Enum DoesNotIncludeAny for value: doesNotIncludeAny
            /// </summary>
            [EnumMember(Value = "doesNotIncludeAny")]
            DoesNotIncludeAny = 9        }
        /// <summary>
        /// Choose from a number of different operators
        /// </summary>
        /// <value>Choose from a number of different operators</value>
        [DataMember(Name="operator", EmitDefaultValue=false)]
        public OperatorEnum Operator { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FunctionBarrier" /> class.
        /// </summary>
        /// <param name="functionType">Choose from a number of different calculation functions. (required).</param>
        /// <param name="networkAttributeName">Choose to filter by any network attribute defined in the system. (required).</param>
        /// <param name="_operator">Choose from a number of different operators (required).</param>
        /// <param name="value">Specific value of the input attribute type that, if discovered, will cause the termination.(string (numeric) (required).</param>
        /// <param name="useLocalValues">Calculates values in each direction as opposed to an overall global value..</param>
        public FunctionBarrier(FunctionTypeEnum functionType = default(FunctionTypeEnum), string networkAttributeName = default(string), OperatorEnum _operator = default(OperatorEnum), string value = default(string), bool? useLocalValues = default(bool?))
        {
            // to ensure "functionType" is required (not null)
            if (functionType == null)
            {
                throw new InvalidDataException("functionType is a required property for FunctionBarrier and cannot be null");
            }
            else
            {
                this.FunctionType = functionType;
            }
            // to ensure "networkAttributeName" is required (not null)
            if (networkAttributeName == null)
            {
                throw new InvalidDataException("networkAttributeName is a required property for FunctionBarrier and cannot be null");
            }
            else
            {
                this.NetworkAttributeName = networkAttributeName;
            }
            // to ensure "_operator" is required (not null)
            if (_operator == null)
            {
                throw new InvalidDataException("_operator is a required property for FunctionBarrier and cannot be null");
            }
            else
            {
                this.Operator = _operator;
            }
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new InvalidDataException("value is a required property for FunctionBarrier and cannot be null");
            }
            else
            {
                this.Value = value;
            }
            this.UseLocalValues = useLocalValues;
        }
        

        /// <summary>
        /// Choose to filter by any network attribute defined in the system.
        /// </summary>
        /// <value>Choose to filter by any network attribute defined in the system.</value>
        [DataMember(Name="networkAttributeName", EmitDefaultValue=false)]
        public string NetworkAttributeName { get; set; }


        /// <summary>
        /// Specific value of the input attribute type that, if discovered, will cause the termination.(string (numeric)
        /// </summary>
        /// <value>Specific value of the input attribute type that, if discovered, will cause the termination.(string (numeric)</value>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public string Value { get; set; }

        /// <summary>
        /// Calculates values in each direction as opposed to an overall global value.
        /// </summary>
        /// <value>Calculates values in each direction as opposed to an overall global value.</value>
        [DataMember(Name="useLocalValues", EmitDefaultValue=false)]
        public bool? UseLocalValues { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FunctionBarrier {\n");
            sb.Append("  FunctionType: ").Append(FunctionType).Append("\n");
            sb.Append("  NetworkAttributeName: ").Append(NetworkAttributeName).Append("\n");
            sb.Append("  Operator: ").Append(Operator).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  UseLocalValues: ").Append(UseLocalValues).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FunctionBarrier);
        }

        /// <summary>
        /// Returns true if FunctionBarrier instances are equal
        /// </summary>
        /// <param name="input">Instance of FunctionBarrier to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FunctionBarrier input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FunctionType == input.FunctionType ||
                    (this.FunctionType != null &&
                    this.FunctionType.Equals(input.FunctionType))
                ) && 
                (
                    this.NetworkAttributeName == input.NetworkAttributeName ||
                    (this.NetworkAttributeName != null &&
                    this.NetworkAttributeName.Equals(input.NetworkAttributeName))
                ) && 
                (
                    this.Operator == input.Operator ||
                    (this.Operator != null &&
                    this.Operator.Equals(input.Operator))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                ) && 
                (
                    this.UseLocalValues == input.UseLocalValues ||
                    (this.UseLocalValues != null &&
                    this.UseLocalValues.Equals(input.UseLocalValues))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FunctionType != null)
                    hashCode = hashCode * 59 + this.FunctionType.GetHashCode();
                if (this.NetworkAttributeName != null)
                    hashCode = hashCode * 59 + this.NetworkAttributeName.GetHashCode();
                if (this.Operator != null)
                    hashCode = hashCode * 59 + this.Operator.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                if (this.UseLocalValues != null)
                    hashCode = hashCode * 59 + this.UseLocalValues.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
