/* 
 * Swagger for Utility Network
 *
 * Open API Specification (OAS/Swagger)  * **trace**, **updateIsConnected** from the [ArcGIS Utility Network](https://developers.arcgis.com/rest/services-reference/utility-network-service.htm) * **generateToken** from the [ArcGIS REST API](https://developers.arcgis.com/rest/)  Tested on ArcGIS  Enterprise 10.8.1 using OpenAPI Specification (OAC) written in [SwaggerEditor](https://github.com/swagger-api/swagger-editor)   and [SwaggerHub](https://app.swaggerhub.com/) for C# and Typescript-Angular code generation.  
 *
 * OpenAPI spec version: 3.0
 * Contact: kim.sundeen@sspinnovations.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// NetworkAttribute
    /// </summary>
    [DataContract]
        public partial class NetworkAttribute :  IEquatable<NetworkAttribute>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkAttribute" /> class.
        /// </summary>
        /// <param name="networkAttribute">networkAttribute.</param>
        public NetworkAttribute(decimal? networkAttribute = default(decimal?))
        {
            this._NetworkAttribute = networkAttribute;
        }
        
        /// <summary>
        /// Gets or Sets _NetworkAttribute
        /// </summary>
        [DataMember(Name="networkAttribute", EmitDefaultValue=false)]
        public decimal? _NetworkAttribute { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NetworkAttribute {\n");
            sb.Append("  _NetworkAttribute: ").Append(_NetworkAttribute).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NetworkAttribute);
        }

        /// <summary>
        /// Returns true if NetworkAttribute instances are equal
        /// </summary>
        /// <param name="input">Instance of NetworkAttribute to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NetworkAttribute input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._NetworkAttribute == input._NetworkAttribute ||
                    (this._NetworkAttribute != null &&
                    this._NetworkAttribute.Equals(input._NetworkAttribute))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._NetworkAttribute != null)
                    hashCode = hashCode * 59 + this._NetworkAttribute.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
