/**
 * Swagger for Utility Network
 * Open API Specification (OAS/Swagger)  * **trace**, **updateIsConnected** from the [ArcGIS Utility Network]( https://developers.arcgis.com/rest/services-reference/utility-network-service.htm) * **generateToken** from the [ArcGIS REST API](https://developers.arcgis.com/rest/)  Tested on ArcGIS  Enterprise 10.6.1 using [NSwagStudio](https://github.com/RSuter/NSwag/wiki/NSwagStudio) C# code gen . 
 *
 * OpenAPI spec version: 0.13
 * Contact: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.UpdateIsConnectedResponse
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * UtilityNetworkService
   * 
   * Expected answers:
   *   code 200 : UpdateIsConnectedResponse (Status 200)
   * 
   * @param serverWebAdaptor 
   * @param utilityNetworkName 
   * @param `f` 
   * @param token 
   */
  def serverWebAdaptorRestServicesUtilityNetworkNameUtilityNetworkServerUpdateIsConnectedPost(serverWebAdaptor: String, utilityNetworkName: String, `f`: String, token: String): ApiRequest[UpdateIsConnectedResponse] =
    ApiRequest[UpdateIsConnectedResponse](ApiMethods.POST, "https://t4e7j4g.restletmocks.net", "/{ServerWebAdaptor}/rest/services/{UtilityNetworkName}/UtilityNetworkServer/updateIsConnected", "application/json")
      .withQueryParam("f", `f`)
      .withQueryParam("token", token)
      .withPathParam("ServerWebAdaptor", serverWebAdaptor)
      .withPathParam("UtilityNetworkName", utilityNetworkName)
      .withSuccessResponse[UpdateIsConnectedResponse](200)
      

}

