/* 
 * Swagger for Utility Network
 *
 * Open API Specification (OAS/Swagger)  * **trace**, **updateIsConnected** from the [ArcGIS Utility Network](https://developers.arcgis.com/rest/services-reference/utility-network-service.htm) * **generateToken** from the [ArcGIS REST API](https://developers.arcgis.com/rest/)  Tested on ArcGIS  Enterprise 10.8.1 using OpenAPI Specification (OAC) written in [SwaggerEditor](https://github.com/swagger-api/swagger-editor)   and [SwaggerHub](https://app.swaggerhub.com/) for C# and Typescript-Angular code generation.  
 *
 * OpenAPI spec version: 3.0
 * Contact: kim.sundeen@sspinnovations.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Body1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Body1Tests
    {
        // TODO uncomment below to declare an instance variable for Body1
        //private Body1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Body1
            //instance = new Body1();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Body1
        /// </summary>
        [Test]
        public void Body1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Body1
            //Assert.IsInstanceOfType<Body1> (instance, "variable 'instance' is a Body1");
        }


        /// <summary>
        /// Test the property 'F'
        /// </summary>
        [Test]
        public void FTest()
        {
            // TODO unit test for the property 'F'
        }
        /// <summary>
        /// Test the property 'GdbVersion'
        /// </summary>
        [Test]
        public void GdbVersionTest()
        {
            // TODO unit test for the property 'GdbVersion'
        }
        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Test]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }
        /// <summary>
        /// Test the property 'Moment'
        /// </summary>
        [Test]
        public void MomentTest()
        {
            // TODO unit test for the property 'Moment'
        }
        /// <summary>
        /// Test the property 'TraceType'
        /// </summary>
        [Test]
        public void TraceTypeTest()
        {
            // TODO unit test for the property 'TraceType'
        }
        /// <summary>
        /// Test the property 'TraceLocations'
        /// </summary>
        [Test]
        public void TraceLocationsTest()
        {
            // TODO unit test for the property 'TraceLocations'
        }
        /// <summary>
        /// Test the property 'TraceConfiguration'
        /// </summary>
        [Test]
        public void TraceConfigurationTest()
        {
            // TODO unit test for the property 'TraceConfiguration'
        }
        /// <summary>
        /// Test the property 'ResultTypes'
        /// </summary>
        [Test]
        public void ResultTypesTest()
        {
            // TODO unit test for the property 'ResultTypes'
        }

    }

}
