/* 
 * Swagger for Utility Network
 *
 * Open API Specification (OAS/Swagger)  * **trace**, **updateIsConnected** from the [ArcGIS Utility Network](https://developers.arcgis.com/rest/services-reference/utility-network-service.htm) * **generateToken** from the [ArcGIS REST API](https://developers.arcgis.com/rest/)  Tested on ArcGIS  Enterprise 10.8.1 using OpenAPI Specification (OAC) written in [SwaggerEditor](https://github.com/swagger-api/swagger-editor)   and [SwaggerHub](https://app.swaggerhub.com/) for C# and Typescript-Angular code generation.  
 *
 * OpenAPI spec version: 3.0
 * Contact: kim.sundeen@sspinnovations.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TraceResultsSetTraceResultsElements
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TraceResultsSetTraceResultsElementsTests
    {
        // TODO uncomment below to declare an instance variable for TraceResultsSetTraceResultsElements
        //private TraceResultsSetTraceResultsElements instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TraceResultsSetTraceResultsElements
            //instance = new TraceResultsSetTraceResultsElements();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TraceResultsSetTraceResultsElements
        /// </summary>
        [Test]
        public void TraceResultsSetTraceResultsElementsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TraceResultsSetTraceResultsElements
            //Assert.IsInstanceOfType<TraceResultsSetTraceResultsElements> (instance, "variable 'instance' is a TraceResultsSetTraceResultsElements");
        }


        /// <summary>
        /// Test the property 'NetworkSourceId'
        /// </summary>
        [Test]
        public void NetworkSourceIdTest()
        {
            // TODO unit test for the property 'NetworkSourceId'
        }
        /// <summary>
        /// Test the property 'GlobalId'
        /// </summary>
        [Test]
        public void GlobalIdTest()
        {
            // TODO unit test for the property 'GlobalId'
        }
        /// <summary>
        /// Test the property 'ObjectId'
        /// </summary>
        [Test]
        public void ObjectIdTest()
        {
            // TODO unit test for the property 'ObjectId'
        }
        /// <summary>
        /// Test the property 'TerminalId'
        /// </summary>
        [Test]
        public void TerminalIdTest()
        {
            // TODO unit test for the property 'TerminalId'
        }
        /// <summary>
        /// Test the property 'AssetGroupCode'
        /// </summary>
        [Test]
        public void AssetGroupCodeTest()
        {
            // TODO unit test for the property 'AssetGroupCode'
        }
        /// <summary>
        /// Test the property 'AssetTypeCode'
        /// </summary>
        [Test]
        public void AssetTypeCodeTest()
        {
            // TODO unit test for the property 'AssetTypeCode'
        }

    }

}
