/**
 * Swagger for Utility Network
 * Open API Specification (OAS/Swagger)  * **trace**, **updateIsConnected** from the [ArcGIS Utility Network]( https://developers.arcgis.com/rest/services-reference/utility-network-service.htm) * **generateToken** from the [ArcGIS REST API](https://developers.arcgis.com/rest/)  Tested on ArcGIS  Enterprise 10.6.1 using [NSwagStudio](https://github.com/RSuter/NSwag/wiki/NSwagStudio) C# code gen . 
 *
 * OpenAPI spec version: 0.13
 * Contact: 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * TokenResponse_error.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_TokenResponse_error_H_
#define IO_SWAGGER_CLIENT_MODEL_TokenResponse_error_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  TokenResponse_error
    : public ModelBase
{
public:
    TokenResponse_error();
    virtual ~TokenResponse_error();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// TokenResponse_error members

    /// <summary>
    /// 
    /// </summary>
    double getCode() const;
    bool codeIsSet() const;
    void unsetCode();
    void setCode(double value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getMessage() const;
    bool messageIsSet() const;
    void unsetMessage();
    void setMessage(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getDetails();
    bool detailsIsSet() const;
    void unsetDetails();
    void setDetails(std::vector<utility::string_t> value);

protected:
    double m_Code;
    bool m_CodeIsSet;
    utility::string_t m_Message;
    bool m_MessageIsSet;
    std::vector<utility::string_t> m_Details;
    bool m_DetailsIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_TokenResponse_error_H_ */
